- hosts: server
  tasks:
  # IP Address Section
  - name: Change IP address  
    become: yes    
    shell: |
      echo \
      'network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            dhcp4: false
            dhcp6: false
            addresses:
              - '{{ server_address }}'/24
            gateway4: '{{ gateway_address }}'
            nameservers:
              addresses:
                - '{{ gateway_address }}'' > /etc/netplan/99-network.yaml      
  
  # Hostname Section
  - name: Change a Hostname
    become: yes
    shell: |
       hostnamectl set-hostname '{{ hostname }}'

  # Reboot Section
  - name: Execute reboot
    become: yes
    shell: |
       sleep 2 && reboot
    async: 1
    poll: 0
  - name: Wait for SSH port down
    wait_for:
      host: '{{ server_address }}'
      port: 22
      state: stopped
    delegate_to: 127.0.0.1
  - name: Wait for SSH port up
    wait_for:
      host: '{{ server_address }}'
      port: 22
      state: started
    delegate_to: 127.0.0.1    
  - name: Debug
    debug:
      msg: Finish!